# Generated by Django 4.1.2 on 2022-10-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGrado', models.CharField(max_length=100)),
                ('imgGrado', models.ImageField(upload_to='grados')),
            ],
        ),
    ]
