# Generated by Django 4.1.2 on 2022-10-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMateria', models.CharField(max_length=100)),
                ('imgMateria', models.ImageField(default='img/educa.png', upload_to='materias')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.grados')),
            ],
        ),
    ]
