# Generated by Django 4.1.2 on 2022-10-28 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemasMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTema', models.CharField(max_length=255)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.materias')),
            ],
        ),
    ]
