# Generated by Django 4.1.2 on 2022-10-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_subtemasmateria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grados',
            options={'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterField(
            model_name='subtemasmateria',
            name='descripcionSubTema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
