# Generated by Django 4.1.2 on 2022-10-31 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_remove_subtemasmateria_descripcionsubtema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materias',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='recursos',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterModelOptions(
            name='subtemasmateria',
            options={'verbose_name': 'Sub Temas Materia', 'verbose_name_plural': 'Sub Temas Materia'},
        ),
        migrations.AlterModelOptions(
            name='temasmaterias',
            options={'verbose_name': 'Temas Materia', 'verbose_name_plural': 'Temas Materia'},
        ),
    ]
